# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ce908c798700b73d69faa3269f39e17e60ba6ba524339116c7355917398b70cba7b6cde2cf58faf573a0e7af3e20e058ea9be2bd8bea05bd704ef0752ca912a6

test:
  secret_key_base: 67fbd8d6bf45a55083249911afa3a87e4a4d387f0da0ad4d066c889e02690fb3b7145828630e7353add170267f0ebd480e4f6ebb9063c28c96e7a3f27c2aa97a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
